namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: rismitaghosh/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    cpu: 500m
    memory: 128Mi

containers:
  ports:
    containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
